// Generated by gencpp from file config_server/GetParameter.msg
// DO NOT EDIT!


#ifndef CONFIG_SERVER_MESSAGE_GETPARAMETER_H
#define CONFIG_SERVER_MESSAGE_GETPARAMETER_H

#include <ros/service_traits.h>


#include <config_server/GetParameterRequest.h>
#include <config_server/GetParameterResponse.h>


namespace config_server
{

struct GetParameter
{

typedef GetParameterRequest Request;
typedef GetParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetParameter
} // namespace config_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::config_server::GetParameter > {
  static const char* value()
  {
    return "f20c32a0b2a08c9ecdba58674ac1438f";
  }

  static const char* value(const ::config_server::GetParameter&) { return value(); }
};

template<>
struct DataType< ::config_server::GetParameter > {
  static const char* value()
  {
    return "config_server/GetParameter";
  }

  static const char* value(const ::config_server::GetParameter&) { return value(); }
};


// service_traits::MD5Sum< ::config_server::GetParameterRequest> should match
// service_traits::MD5Sum< ::config_server::GetParameter >
template<>
struct MD5Sum< ::config_server::GetParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::config_server::GetParameter >::value();
  }
  static const char* value(const ::config_server::GetParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::config_server::GetParameterRequest> should match
// service_traits::DataType< ::config_server::GetParameter >
template<>
struct DataType< ::config_server::GetParameterRequest>
{
  static const char* value()
  {
    return DataType< ::config_server::GetParameter >::value();
  }
  static const char* value(const ::config_server::GetParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::config_server::GetParameterResponse> should match
// service_traits::MD5Sum< ::config_server::GetParameter >
template<>
struct MD5Sum< ::config_server::GetParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::config_server::GetParameter >::value();
  }
  static const char* value(const ::config_server::GetParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::config_server::GetParameterResponse> should match
// service_traits::DataType< ::config_server::GetParameter >
template<>
struct DataType< ::config_server::GetParameterResponse>
{
  static const char* value()
  {
    return DataType< ::config_server::GetParameter >::value();
  }
  static const char* value(const ::config_server::GetParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONFIG_SERVER_MESSAGE_GETPARAMETER_H
