// Generated by gencpp from file config_server/ParameterList.msg
// DO NOT EDIT!


#ifndef CONFIG_SERVER_MESSAGE_PARAMETERLIST_H
#define CONFIG_SERVER_MESSAGE_PARAMETERLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <config_server/ParameterDescription.h>

namespace config_server
{
template <class ContainerAllocator>
struct ParameterList_
{
  typedef ParameterList_<ContainerAllocator> Type;

  ParameterList_()
    : parameters()  {
    }
  ParameterList_(const ContainerAllocator& _alloc)
    : parameters(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::config_server::ParameterDescription_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::config_server::ParameterDescription_<ContainerAllocator> >> _parameters_type;
  _parameters_type parameters;





  typedef boost::shared_ptr< ::config_server::ParameterList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::config_server::ParameterList_<ContainerAllocator> const> ConstPtr;

}; // struct ParameterList_

typedef ::config_server::ParameterList_<std::allocator<void> > ParameterList;

typedef boost::shared_ptr< ::config_server::ParameterList > ParameterListPtr;
typedef boost::shared_ptr< ::config_server::ParameterList const> ParameterListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::config_server::ParameterList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::config_server::ParameterList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::config_server::ParameterList_<ContainerAllocator1> & lhs, const ::config_server::ParameterList_<ContainerAllocator2> & rhs)
{
  return lhs.parameters == rhs.parameters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::config_server::ParameterList_<ContainerAllocator1> & lhs, const ::config_server::ParameterList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace config_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::config_server::ParameterList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::config_server::ParameterList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config_server::ParameterList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config_server::ParameterList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config_server::ParameterList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config_server::ParameterList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::config_server::ParameterList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b43150e18cd687d16ddbddaf1454c72c";
  }

  static const char* value(const ::config_server::ParameterList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb43150e18cd687d1ULL;
  static const uint64_t static_value2 = 0x6ddbddaf1454c72cULL;
};

template<class ContainerAllocator>
struct DataType< ::config_server::ParameterList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "config_server/ParameterList";
  }

  static const char* value(const ::config_server::ParameterList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::config_server::ParameterList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ParameterDescription[] parameters\n"
"================================================================================\n"
"MSG: config_server/ParameterDescription\n"
"string name\n"
"string type\n"
"float32 min\n"
"float32 max\n"
"float32 step\n"
"string default_value\n"
;
  }

  static const char* value(const ::config_server::ParameterList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::config_server::ParameterList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.parameters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ParameterList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::config_server::ParameterList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::config_server::ParameterList_<ContainerAllocator>& v)
  {
    s << indent << "parameters[]" << std::endl;
    for (size_t i = 0; i < v.parameters.size(); ++i)
    {
      s << indent << "  parameters[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::config_server::ParameterDescription_<ContainerAllocator> >::stream(s, indent + "    ", v.parameters[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONFIG_SERVER_MESSAGE_PARAMETERLIST_H
