// Generated by gencpp from file config_server/SaveResponse.msg
// DO NOT EDIT!


#ifndef CONFIG_SERVER_MESSAGE_SAVERESPONSE_H
#define CONFIG_SERVER_MESSAGE_SAVERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace config_server
{
template <class ContainerAllocator>
struct SaveResponse_
{
  typedef SaveResponse_<ContainerAllocator> Type;

  SaveResponse_()
    {
    }
  SaveResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::config_server::SaveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::config_server::SaveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveResponse_

typedef ::config_server::SaveResponse_<std::allocator<void> > SaveResponse;

typedef boost::shared_ptr< ::config_server::SaveResponse > SaveResponsePtr;
typedef boost::shared_ptr< ::config_server::SaveResponse const> SaveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::config_server::SaveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::config_server::SaveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace config_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::config_server::SaveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::config_server::SaveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config_server::SaveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config_server::SaveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config_server::SaveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config_server::SaveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::config_server::SaveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::config_server::SaveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::config_server::SaveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "config_server/SaveResponse";
  }

  static const char* value(const ::config_server::SaveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::config_server::SaveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::config_server::SaveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::config_server::SaveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::config_server::SaveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::config_server::SaveResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CONFIG_SERVER_MESSAGE_SAVERESPONSE_H
