// Generated by gencpp from file config_server/Save.msg
// DO NOT EDIT!


#ifndef CONFIG_SERVER_MESSAGE_SAVE_H
#define CONFIG_SERVER_MESSAGE_SAVE_H

#include <ros/service_traits.h>


#include <config_server/SaveRequest.h>
#include <config_server/SaveResponse.h>


namespace config_server
{

struct Save
{

typedef SaveRequest Request;
typedef SaveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Save
} // namespace config_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::config_server::Save > {
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::config_server::Save&) { return value(); }
};

template<>
struct DataType< ::config_server::Save > {
  static const char* value()
  {
    return "config_server/Save";
  }

  static const char* value(const ::config_server::Save&) { return value(); }
};


// service_traits::MD5Sum< ::config_server::SaveRequest> should match
// service_traits::MD5Sum< ::config_server::Save >
template<>
struct MD5Sum< ::config_server::SaveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::config_server::Save >::value();
  }
  static const char* value(const ::config_server::SaveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::config_server::SaveRequest> should match
// service_traits::DataType< ::config_server::Save >
template<>
struct DataType< ::config_server::SaveRequest>
{
  static const char* value()
  {
    return DataType< ::config_server::Save >::value();
  }
  static const char* value(const ::config_server::SaveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::config_server::SaveResponse> should match
// service_traits::MD5Sum< ::config_server::Save >
template<>
struct MD5Sum< ::config_server::SaveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::config_server::Save >::value();
  }
  static const char* value(const ::config_server::SaveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::config_server::SaveResponse> should match
// service_traits::DataType< ::config_server::Save >
template<>
struct DataType< ::config_server::SaveResponse>
{
  static const char* value()
  {
    return DataType< ::config_server::Save >::value();
  }
  static const char* value(const ::config_server::SaveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONFIG_SERVER_MESSAGE_SAVE_H
