// Generated by gencpp from file config_server/SetParameterRequest.msg
// DO NOT EDIT!


#ifndef CONFIG_SERVER_MESSAGE_SETPARAMETERREQUEST_H
#define CONFIG_SERVER_MESSAGE_SETPARAMETERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace config_server
{
template <class ContainerAllocator>
struct SetParameterRequest_
{
  typedef SetParameterRequest_<ContainerAllocator> Type;

  SetParameterRequest_()
    : name()
    , value()
    , no_notify()  {
    }
  SetParameterRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , value(_alloc)
    , no_notify(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _value_type;
  _value_type value;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _no_notify_type;
  _no_notify_type no_notify;





  typedef boost::shared_ptr< ::config_server::SetParameterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::config_server::SetParameterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetParameterRequest_

typedef ::config_server::SetParameterRequest_<std::allocator<void> > SetParameterRequest;

typedef boost::shared_ptr< ::config_server::SetParameterRequest > SetParameterRequestPtr;
typedef boost::shared_ptr< ::config_server::SetParameterRequest const> SetParameterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::config_server::SetParameterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::config_server::SetParameterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::config_server::SetParameterRequest_<ContainerAllocator1> & lhs, const ::config_server::SetParameterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.value == rhs.value &&
    lhs.no_notify == rhs.no_notify;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::config_server::SetParameterRequest_<ContainerAllocator1> & lhs, const ::config_server::SetParameterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace config_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::config_server::SetParameterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::config_server::SetParameterRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config_server::SetParameterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config_server::SetParameterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config_server::SetParameterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config_server::SetParameterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::config_server::SetParameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec7a3cf3b2b316cbec7051b32ed868f7";
  }

  static const char* value(const ::config_server::SetParameterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec7a3cf3b2b316cbULL;
  static const uint64_t static_value2 = 0xec7051b32ed868f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::config_server::SetParameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "config_server/SetParameterRequest";
  }

  static const char* value(const ::config_server::SetParameterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::config_server::SetParameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"string value\n"
"string no_notify\n"
;
  }

  static const char* value(const ::config_server::SetParameterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::config_server::SetParameterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.value);
      stream.next(m.no_notify);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetParameterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::config_server::SetParameterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::config_server::SetParameterRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.value);
    s << indent << "no_notify: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.no_notify);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONFIG_SERVER_MESSAGE_SETPARAMETERREQUEST_H
