// Generated by gencpp from file config_server/SetParameter.msg
// DO NOT EDIT!


#ifndef CONFIG_SERVER_MESSAGE_SETPARAMETER_H
#define CONFIG_SERVER_MESSAGE_SETPARAMETER_H

#include <ros/service_traits.h>


#include <config_server/SetParameterRequest.h>
#include <config_server/SetParameterResponse.h>


namespace config_server
{

struct SetParameter
{

typedef SetParameterRequest Request;
typedef SetParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetParameter
} // namespace config_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::config_server::SetParameter > {
  static const char* value()
  {
    return "ec7a3cf3b2b316cbec7051b32ed868f7";
  }

  static const char* value(const ::config_server::SetParameter&) { return value(); }
};

template<>
struct DataType< ::config_server::SetParameter > {
  static const char* value()
  {
    return "config_server/SetParameter";
  }

  static const char* value(const ::config_server::SetParameter&) { return value(); }
};


// service_traits::MD5Sum< ::config_server::SetParameterRequest> should match
// service_traits::MD5Sum< ::config_server::SetParameter >
template<>
struct MD5Sum< ::config_server::SetParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::config_server::SetParameter >::value();
  }
  static const char* value(const ::config_server::SetParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::config_server::SetParameterRequest> should match
// service_traits::DataType< ::config_server::SetParameter >
template<>
struct DataType< ::config_server::SetParameterRequest>
{
  static const char* value()
  {
    return DataType< ::config_server::SetParameter >::value();
  }
  static const char* value(const ::config_server::SetParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::config_server::SetParameterResponse> should match
// service_traits::MD5Sum< ::config_server::SetParameter >
template<>
struct MD5Sum< ::config_server::SetParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::config_server::SetParameter >::value();
  }
  static const char* value(const ::config_server::SetParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::config_server::SetParameterResponse> should match
// service_traits::DataType< ::config_server::SetParameter >
template<>
struct DataType< ::config_server::SetParameterResponse>
{
  static const char* value()
  {
    return DataType< ::config_server::SetParameter >::value();
  }
  static const char* value(const ::config_server::SetParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONFIG_SERVER_MESSAGE_SETPARAMETER_H
