// Generated by gencpp from file config_server/SubscribeListResponse.msg
// DO NOT EDIT!


#ifndef CONFIG_SERVER_MESSAGE_SUBSCRIBELISTRESPONSE_H
#define CONFIG_SERVER_MESSAGE_SUBSCRIBELISTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace config_server
{
template <class ContainerAllocator>
struct SubscribeListResponse_
{
  typedef SubscribeListResponse_<ContainerAllocator> Type;

  SubscribeListResponse_()
    : values()  {
    }
  SubscribeListResponse_(const ContainerAllocator& _alloc)
    : values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::config_server::SubscribeListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::config_server::SubscribeListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SubscribeListResponse_

typedef ::config_server::SubscribeListResponse_<std::allocator<void> > SubscribeListResponse;

typedef boost::shared_ptr< ::config_server::SubscribeListResponse > SubscribeListResponsePtr;
typedef boost::shared_ptr< ::config_server::SubscribeListResponse const> SubscribeListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::config_server::SubscribeListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::config_server::SubscribeListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::config_server::SubscribeListResponse_<ContainerAllocator1> & lhs, const ::config_server::SubscribeListResponse_<ContainerAllocator2> & rhs)
{
  return lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::config_server::SubscribeListResponse_<ContainerAllocator1> & lhs, const ::config_server::SubscribeListResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace config_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::config_server::SubscribeListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::config_server::SubscribeListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config_server::SubscribeListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config_server::SubscribeListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config_server::SubscribeListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config_server::SubscribeListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::config_server::SubscribeListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b574a4a611cba2b6cf401af98173eb55";
  }

  static const char* value(const ::config_server::SubscribeListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb574a4a611cba2b6ULL;
  static const uint64_t static_value2 = 0xcf401af98173eb55ULL;
};

template<class ContainerAllocator>
struct DataType< ::config_server::SubscribeListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "config_server/SubscribeListResponse";
  }

  static const char* value(const ::config_server::SubscribeListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::config_server::SubscribeListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] values\n"
;
  }

  static const char* value(const ::config_server::SubscribeListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::config_server::SubscribeListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubscribeListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::config_server::SubscribeListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::config_server::SubscribeListResponse_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONFIG_SERVER_MESSAGE_SUBSCRIBELISTRESPONSE_H
