// Generated by gencpp from file config_server/SubscribeListRequest.msg
// DO NOT EDIT!


#ifndef CONFIG_SERVER_MESSAGE_SUBSCRIBELISTREQUEST_H
#define CONFIG_SERVER_MESSAGE_SUBSCRIBELISTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <config_server/ParameterDescription.h>

namespace config_server
{
template <class ContainerAllocator>
struct SubscribeListRequest_
{
  typedef SubscribeListRequest_<ContainerAllocator> Type;

  SubscribeListRequest_()
    : callback()
    , parameters()  {
    }
  SubscribeListRequest_(const ContainerAllocator& _alloc)
    : callback(_alloc)
    , parameters(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _callback_type;
  _callback_type callback;

   typedef std::vector< ::config_server::ParameterDescription_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::config_server::ParameterDescription_<ContainerAllocator> >> _parameters_type;
  _parameters_type parameters;





  typedef boost::shared_ptr< ::config_server::SubscribeListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::config_server::SubscribeListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SubscribeListRequest_

typedef ::config_server::SubscribeListRequest_<std::allocator<void> > SubscribeListRequest;

typedef boost::shared_ptr< ::config_server::SubscribeListRequest > SubscribeListRequestPtr;
typedef boost::shared_ptr< ::config_server::SubscribeListRequest const> SubscribeListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::config_server::SubscribeListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::config_server::SubscribeListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::config_server::SubscribeListRequest_<ContainerAllocator1> & lhs, const ::config_server::SubscribeListRequest_<ContainerAllocator2> & rhs)
{
  return lhs.callback == rhs.callback &&
    lhs.parameters == rhs.parameters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::config_server::SubscribeListRequest_<ContainerAllocator1> & lhs, const ::config_server::SubscribeListRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace config_server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::config_server::SubscribeListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::config_server::SubscribeListRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config_server::SubscribeListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::config_server::SubscribeListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config_server::SubscribeListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::config_server::SubscribeListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::config_server::SubscribeListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80f357f33862d1f4851d8f3fef90397e";
  }

  static const char* value(const ::config_server::SubscribeListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80f357f33862d1f4ULL;
  static const uint64_t static_value2 = 0x851d8f3fef90397eULL;
};

template<class ContainerAllocator>
struct DataType< ::config_server::SubscribeListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "config_server/SubscribeListRequest";
  }

  static const char* value(const ::config_server::SubscribeListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::config_server::SubscribeListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string callback\n"
"ParameterDescription[] parameters\n"
"\n"
"================================================================================\n"
"MSG: config_server/ParameterDescription\n"
"string name\n"
"string type\n"
"float32 min\n"
"float32 max\n"
"float32 step\n"
"string default_value\n"
;
  }

  static const char* value(const ::config_server::SubscribeListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::config_server::SubscribeListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.callback);
      stream.next(m.parameters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SubscribeListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::config_server::SubscribeListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::config_server::SubscribeListRequest_<ContainerAllocator>& v)
  {
    s << indent << "callback: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.callback);
    s << indent << "parameters[]" << std::endl;
    for (size_t i = 0; i < v.parameters.size(); ++i)
    {
      s << indent << "  parameters[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::config_server::ParameterDescription_<ContainerAllocator> >::stream(s, indent + "    ", v.parameters[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONFIG_SERVER_MESSAGE_SUBSCRIBELISTREQUEST_H
