// Generated by gencpp from file config_server/SubscribeList.msg
// DO NOT EDIT!


#ifndef CONFIG_SERVER_MESSAGE_SUBSCRIBELIST_H
#define CONFIG_SERVER_MESSAGE_SUBSCRIBELIST_H

#include <ros/service_traits.h>


#include <config_server/SubscribeListRequest.h>
#include <config_server/SubscribeListResponse.h>


namespace config_server
{

struct SubscribeList
{

typedef SubscribeListRequest Request;
typedef SubscribeListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SubscribeList
} // namespace config_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::config_server::SubscribeList > {
  static const char* value()
  {
    return "b3d53d10785172ca95ba19fea29582f8";
  }

  static const char* value(const ::config_server::SubscribeList&) { return value(); }
};

template<>
struct DataType< ::config_server::SubscribeList > {
  static const char* value()
  {
    return "config_server/SubscribeList";
  }

  static const char* value(const ::config_server::SubscribeList&) { return value(); }
};


// service_traits::MD5Sum< ::config_server::SubscribeListRequest> should match
// service_traits::MD5Sum< ::config_server::SubscribeList >
template<>
struct MD5Sum< ::config_server::SubscribeListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::config_server::SubscribeList >::value();
  }
  static const char* value(const ::config_server::SubscribeListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::config_server::SubscribeListRequest> should match
// service_traits::DataType< ::config_server::SubscribeList >
template<>
struct DataType< ::config_server::SubscribeListRequest>
{
  static const char* value()
  {
    return DataType< ::config_server::SubscribeList >::value();
  }
  static const char* value(const ::config_server::SubscribeListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::config_server::SubscribeListResponse> should match
// service_traits::MD5Sum< ::config_server::SubscribeList >
template<>
struct MD5Sum< ::config_server::SubscribeListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::config_server::SubscribeList >::value();
  }
  static const char* value(const ::config_server::SubscribeListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::config_server::SubscribeListResponse> should match
// service_traits::DataType< ::config_server::SubscribeList >
template<>
struct DataType< ::config_server::SubscribeListResponse>
{
  static const char* value()
  {
    return DataType< ::config_server::SubscribeList >::value();
  }
  static const char* value(const ::config_server::SubscribeListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONFIG_SERVER_MESSAGE_SUBSCRIBELIST_H
