// Generated by gencpp from file config_server/Subscribe.msg
// DO NOT EDIT!


#ifndef CONFIG_SERVER_MESSAGE_SUBSCRIBE_H
#define CONFIG_SERVER_MESSAGE_SUBSCRIBE_H

#include <ros/service_traits.h>


#include <config_server/SubscribeRequest.h>
#include <config_server/SubscribeResponse.h>


namespace config_server
{

struct Subscribe
{

typedef SubscribeRequest Request;
typedef SubscribeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Subscribe
} // namespace config_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::config_server::Subscribe > {
  static const char* value()
  {
    return "3aed6858ba7841ecfc55a9e55271bc42";
  }

  static const char* value(const ::config_server::Subscribe&) { return value(); }
};

template<>
struct DataType< ::config_server::Subscribe > {
  static const char* value()
  {
    return "config_server/Subscribe";
  }

  static const char* value(const ::config_server::Subscribe&) { return value(); }
};


// service_traits::MD5Sum< ::config_server::SubscribeRequest> should match
// service_traits::MD5Sum< ::config_server::Subscribe >
template<>
struct MD5Sum< ::config_server::SubscribeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::config_server::Subscribe >::value();
  }
  static const char* value(const ::config_server::SubscribeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::config_server::SubscribeRequest> should match
// service_traits::DataType< ::config_server::Subscribe >
template<>
struct DataType< ::config_server::SubscribeRequest>
{
  static const char* value()
  {
    return DataType< ::config_server::Subscribe >::value();
  }
  static const char* value(const ::config_server::SubscribeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::config_server::SubscribeResponse> should match
// service_traits::MD5Sum< ::config_server::Subscribe >
template<>
struct MD5Sum< ::config_server::SubscribeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::config_server::Subscribe >::value();
  }
  static const char* value(const ::config_server::SubscribeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::config_server::SubscribeResponse> should match
// service_traits::DataType< ::config_server::Subscribe >
template<>
struct DataType< ::config_server::SubscribeResponse>
{
  static const char* value()
  {
    return DataType< ::config_server::Subscribe >::value();
  }
  static const char* value(const ::config_server::SubscribeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONFIG_SERVER_MESSAGE_SUBSCRIBE_H
