; Auto-generated. Do not edit!


(cl:in-package calculate_position_pkg-msg)


;//! \htmlinclude image_points.msg.html

(cl:defclass <image_points> (roslisp-msg-protocol:ros-message)
  ((ball_xyxy
    :reader ball_xyxy
    :initarg :ball_xyxy
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (goalpost_xyxy
    :reader goalpost_xyxy
    :initarg :goalpost_xyxy
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (robot_xyxy
    :reader robot_xyxy
    :initarg :robot_xyxy
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (L_mark_xyxy
    :reader L_mark_xyxy
    :initarg :L_mark_xyxy
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (T_mark_xyxy
    :reader T_mark_xyxy
    :initarg :T_mark_xyxy
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (X_mark_xyxy
    :reader X_mark_xyxy
    :initarg :X_mark_xyxy
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass image_points (<image_points>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <image_points>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'image_points)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name calculate_position_pkg-msg:<image_points> is deprecated: use calculate_position_pkg-msg:image_points instead.")))

(cl:ensure-generic-function 'ball_xyxy-val :lambda-list '(m))
(cl:defmethod ball_xyxy-val ((m <image_points>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader calculate_position_pkg-msg:ball_xyxy-val is deprecated.  Use calculate_position_pkg-msg:ball_xyxy instead.")
  (ball_xyxy m))

(cl:ensure-generic-function 'goalpost_xyxy-val :lambda-list '(m))
(cl:defmethod goalpost_xyxy-val ((m <image_points>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader calculate_position_pkg-msg:goalpost_xyxy-val is deprecated.  Use calculate_position_pkg-msg:goalpost_xyxy instead.")
  (goalpost_xyxy m))

(cl:ensure-generic-function 'robot_xyxy-val :lambda-list '(m))
(cl:defmethod robot_xyxy-val ((m <image_points>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader calculate_position_pkg-msg:robot_xyxy-val is deprecated.  Use calculate_position_pkg-msg:robot_xyxy instead.")
  (robot_xyxy m))

(cl:ensure-generic-function 'L_mark_xyxy-val :lambda-list '(m))
(cl:defmethod L_mark_xyxy-val ((m <image_points>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader calculate_position_pkg-msg:L_mark_xyxy-val is deprecated.  Use calculate_position_pkg-msg:L_mark_xyxy instead.")
  (L_mark_xyxy m))

(cl:ensure-generic-function 'T_mark_xyxy-val :lambda-list '(m))
(cl:defmethod T_mark_xyxy-val ((m <image_points>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader calculate_position_pkg-msg:T_mark_xyxy-val is deprecated.  Use calculate_position_pkg-msg:T_mark_xyxy instead.")
  (T_mark_xyxy m))

(cl:ensure-generic-function 'X_mark_xyxy-val :lambda-list '(m))
(cl:defmethod X_mark_xyxy-val ((m <image_points>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader calculate_position_pkg-msg:X_mark_xyxy-val is deprecated.  Use calculate_position_pkg-msg:X_mark_xyxy instead.")
  (X_mark_xyxy m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <image_points>) ostream)
  "Serializes a message object of type '<image_points>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'ball_xyxy))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'ball_xyxy))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'goalpost_xyxy))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'goalpost_xyxy))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'robot_xyxy))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'robot_xyxy))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'L_mark_xyxy))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'L_mark_xyxy))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'T_mark_xyxy))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'T_mark_xyxy))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'X_mark_xyxy))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'X_mark_xyxy))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <image_points>) istream)
  "Deserializes a message object of type '<image_points>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'ball_xyxy) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'ball_xyxy)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'goalpost_xyxy) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'goalpost_xyxy)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'robot_xyxy) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'robot_xyxy)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'L_mark_xyxy) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'L_mark_xyxy)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'T_mark_xyxy) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'T_mark_xyxy)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'X_mark_xyxy) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'X_mark_xyxy)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<image_points>)))
  "Returns string type for a message object of type '<image_points>"
  "calculate_position_pkg/image_points")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'image_points)))
  "Returns string type for a message object of type 'image_points"
  "calculate_position_pkg/image_points")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<image_points>)))
  "Returns md5sum for a message object of type '<image_points>"
  "df6d256ca807079571778bb4a61cea15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'image_points)))
  "Returns md5sum for a message object of type 'image_points"
  "df6d256ca807079571778bb4a61cea15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<image_points>)))
  "Returns full string definition for message of type '<image_points>"
  (cl:format cl:nil "int32[] ball_xyxy~%int32[] goalpost_xyxy~%int32[] robot_xyxy~%int32[] L_mark_xyxy~%int32[] T_mark_xyxy~%int32[] X_mark_xyxy~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'image_points)))
  "Returns full string definition for message of type 'image_points"
  (cl:format cl:nil "int32[] ball_xyxy~%int32[] goalpost_xyxy~%int32[] robot_xyxy~%int32[] L_mark_xyxy~%int32[] T_mark_xyxy~%int32[] X_mark_xyxy~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <image_points>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'ball_xyxy) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'goalpost_xyxy) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'robot_xyxy) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'L_mark_xyxy) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'T_mark_xyxy) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'X_mark_xyxy) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <image_points>))
  "Converts a ROS message object to a list"
  (cl:list 'image_points
    (cl:cons ':ball_xyxy (ball_xyxy msg))
    (cl:cons ':goalpost_xyxy (goalpost_xyxy msg))
    (cl:cons ':robot_xyxy (robot_xyxy msg))
    (cl:cons ':L_mark_xyxy (L_mark_xyxy msg))
    (cl:cons ':T_mark_xyxy (T_mark_xyxy msg))
    (cl:cons ':X_mark_xyxy (X_mark_xyxy msg))
))
