# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_brain_pkg/head_contol_by_brain.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class head_contol_by_brain(genpy.Message):
  _md5sum = "e40d90720bf88cd6f3200a64bcb87dbc"
  _type = "robot_brain_pkg/head_contol_by_brain"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 neck_rotation_theta_angle  # 颈旋转关节角度
float64 neck_front_swing_theta_angle # 颈前摆关节角度
bool is_find_state # 是否找球状态
bool is_follow_state # 是否跟球状态"""
  __slots__ = ['neck_rotation_theta_angle','neck_front_swing_theta_angle','is_find_state','is_follow_state']
  _slot_types = ['float64','float64','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       neck_rotation_theta_angle,neck_front_swing_theta_angle,is_find_state,is_follow_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(head_contol_by_brain, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.neck_rotation_theta_angle is None:
        self.neck_rotation_theta_angle = 0.
      if self.neck_front_swing_theta_angle is None:
        self.neck_front_swing_theta_angle = 0.
      if self.is_find_state is None:
        self.is_find_state = False
      if self.is_follow_state is None:
        self.is_follow_state = False
    else:
      self.neck_rotation_theta_angle = 0.
      self.neck_front_swing_theta_angle = 0.
      self.is_find_state = False
      self.is_follow_state = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d2B().pack(_x.neck_rotation_theta_angle, _x.neck_front_swing_theta_angle, _x.is_find_state, _x.is_follow_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.neck_rotation_theta_angle, _x.neck_front_swing_theta_angle, _x.is_find_state, _x.is_follow_state,) = _get_struct_2d2B().unpack(str[start:end])
      self.is_find_state = bool(self.is_find_state)
      self.is_follow_state = bool(self.is_follow_state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d2B().pack(_x.neck_rotation_theta_angle, _x.neck_front_swing_theta_angle, _x.is_find_state, _x.is_follow_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.neck_rotation_theta_angle, _x.neck_front_swing_theta_angle, _x.is_find_state, _x.is_follow_state,) = _get_struct_2d2B().unpack(str[start:end])
      self.is_find_state = bool(self.is_find_state)
      self.is_follow_state = bool(self.is_follow_state)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d2B = None
def _get_struct_2d2B():
    global _struct_2d2B
    if _struct_2d2B is None:
        _struct_2d2B = struct.Struct("<2d2B")
    return _struct_2d2B
