(cl:defpackage localization_pkg-msg
  (:use )
  (:export
   "<COMPASSHEADING>"
   "COMPASSHEADING"
   "<DETECTIONS>"
   "DETECTIONS"
   "<LINEDETECTION>"
   "LINEDETECTION"
   "<OBJECTDETECTION>"
   "OBJECTDETECTION"
   "<OBSTACLEDETECTION>"
   "OBSTACLEDETECTION"
   "<PARTICLE>"
   "PARTICLE"
   "<PARTICLESET>"
   "PARTICLESET"
  ))

