// Generated by gencpp from file localization_pkg/Detections.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_PKG_MESSAGE_DETECTIONS_H
#define LOCALIZATION_PKG_MESSAGE_DETECTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <localization_pkg/ObjectDetection.h>
#include <localization_pkg/LineDetection.h>
#include <localization_pkg/ObstacleDetection.h>

namespace localization_pkg
{
template <class ContainerAllocator>
struct Detections_
{
  typedef Detections_<ContainerAllocator> Type;

  Detections_()
    : header()
    , objects()
    , lines()
    , obstacles()  {
    }
  Detections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)
    , lines(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::localization_pkg::ObjectDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::localization_pkg::ObjectDetection_<ContainerAllocator> >> _objects_type;
  _objects_type objects;

   typedef std::vector< ::localization_pkg::LineDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::localization_pkg::LineDetection_<ContainerAllocator> >> _lines_type;
  _lines_type lines;

   typedef std::vector< ::localization_pkg::ObstacleDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::localization_pkg::ObstacleDetection_<ContainerAllocator> >> _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::localization_pkg::Detections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization_pkg::Detections_<ContainerAllocator> const> ConstPtr;

}; // struct Detections_

typedef ::localization_pkg::Detections_<std::allocator<void> > Detections;

typedef boost::shared_ptr< ::localization_pkg::Detections > DetectionsPtr;
typedef boost::shared_ptr< ::localization_pkg::Detections const> DetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization_pkg::Detections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization_pkg::Detections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::localization_pkg::Detections_<ContainerAllocator1> & lhs, const ::localization_pkg::Detections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects &&
    lhs.lines == rhs.lines &&
    lhs.obstacles == rhs.obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::localization_pkg::Detections_<ContainerAllocator1> & lhs, const ::localization_pkg::Detections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace localization_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::localization_pkg::Detections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization_pkg::Detections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization_pkg::Detections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization_pkg::Detections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization_pkg::Detections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization_pkg::Detections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization_pkg::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5a76a8205484ff68b3fae6a670e757f";
  }

  static const char* value(const ::localization_pkg::Detections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5a76a8205484ff6ULL;
  static const uint64_t static_value2 = 0x8b3fae6a670e757fULL;
};

template<class ContainerAllocator>
struct DataType< ::localization_pkg::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization_pkg/Detections";
  }

  static const char* value(const ::localization_pkg::Detections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization_pkg::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"ObjectDetection[] objects\n"
"LineDetection[] lines\n"
"ObstacleDetection[] obstacles\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: localization_pkg/ObjectDetection\n"
"geometry_msgs/Pose2D pose        # Pose\n"
"uint8 type                       # Type (see field_model::WorldObject::Type)\n"
"float32 confidence               # confidence 0..1\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: localization_pkg/LineDetection\n"
"float32 x1\n"
"float32 y1\n"
"float32 x2\n"
"float32 y2\n"
"================================================================================\n"
"MSG: localization_pkg/ObstacleDetection\n"
"geometry_msgs/Point left_lower_corner\n"
"geometry_msgs/Point right_lower_corner\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::localization_pkg::Detections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization_pkg::Detections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
      stream.next(m.lines);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization_pkg::Detections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization_pkg::Detections_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::localization_pkg::ObjectDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
    s << indent << "lines[]" << std::endl;
    for (size_t i = 0; i < v.lines.size(); ++i)
    {
      s << indent << "  lines[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::localization_pkg::LineDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.lines[i]);
    }
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::localization_pkg::ObstacleDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_PKG_MESSAGE_DETECTIONS_H
