// Generated by gencpp from file localization_pkg/LineDetection.msg
// DO NOT EDIT!


#ifndef LOCALIZATION_PKG_MESSAGE_LINEDETECTION_H
#define LOCALIZATION_PKG_MESSAGE_LINEDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace localization_pkg
{
template <class ContainerAllocator>
struct LineDetection_
{
  typedef LineDetection_<ContainerAllocator> Type;

  LineDetection_()
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)  {
    }
  LineDetection_(const ContainerAllocator& _alloc)
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)  {
  (void)_alloc;
    }



   typedef float _x1_type;
  _x1_type x1;

   typedef float _y1_type;
  _y1_type y1;

   typedef float _x2_type;
  _x2_type x2;

   typedef float _y2_type;
  _y2_type y2;





  typedef boost::shared_ptr< ::localization_pkg::LineDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::localization_pkg::LineDetection_<ContainerAllocator> const> ConstPtr;

}; // struct LineDetection_

typedef ::localization_pkg::LineDetection_<std::allocator<void> > LineDetection;

typedef boost::shared_ptr< ::localization_pkg::LineDetection > LineDetectionPtr;
typedef boost::shared_ptr< ::localization_pkg::LineDetection const> LineDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::localization_pkg::LineDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::localization_pkg::LineDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::localization_pkg::LineDetection_<ContainerAllocator1> & lhs, const ::localization_pkg::LineDetection_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::localization_pkg::LineDetection_<ContainerAllocator1> & lhs, const ::localization_pkg::LineDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace localization_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::localization_pkg::LineDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::localization_pkg::LineDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization_pkg::LineDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::localization_pkg::LineDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization_pkg::LineDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::localization_pkg::LineDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::localization_pkg::LineDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d74979d8119401281d48677f845994f";
  }

  static const char* value(const ::localization_pkg::LineDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d74979d81194012ULL;
  static const uint64_t static_value2 = 0x81d48677f845994fULL;
};

template<class ContainerAllocator>
struct DataType< ::localization_pkg::LineDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "localization_pkg/LineDetection";
  }

  static const char* value(const ::localization_pkg::LineDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::localization_pkg::LineDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x1\n"
"float32 y1\n"
"float32 x2\n"
"float32 y2\n"
;
  }

  static const char* value(const ::localization_pkg::LineDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::localization_pkg::LineDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::localization_pkg::LineDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::localization_pkg::LineDetection_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<float>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<float>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<float>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<float>::stream(s, indent + "  ", v.y2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOCALIZATION_PKG_MESSAGE_LINEDETECTION_H
